# Generated by Django 5.1.2 on 2025-11-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('unit_type', models.CharField(blank=True, max_length=100)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Connected', 'Connected'), ('Qualified', 'Qualified'), ('Disqualified', 'Disqualified'), ('FollowUp', 'FollowUp')], default='New', max_length=50)),
                ('last_conversation_date', models.DateField(blank=True, null=True)),
                ('last_conversation_summary', models.TextField(blank=True)),
                ('project_enquired', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
